if (CMAKE_VERSION VERSION_GREATER_EQUAL 3.17)
    include(CheckLanguage)
    check_language(CUDA)
    if(CMAKE_CUDA_COMPILER)
        enable_language(CUDA)
        
        if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.10)
            find_package(CUDAToolkit QUIET)
            set(CUDA_TOOLKIT_INCLUDE ${CUDAToolkit_INCLUDE_DIRS})
        else()
            set(CUDA_FIND_QUIETLY TRUE)
            find_package(CUDA 9.0)
        endif()

        set(CUDA_FOUND TRUE)
        set(CUDA_VERSION_STRING ${CMAKE_CUDA_COMPILER_VERSION})
    else()
        message(STATUS "No CUDA compiler found")
    endif()
else()
    set(CUDA_FIND_QUIETLY TRUE)
    find_package(CUDA 9.0)
endif()

if(CUDA_FOUND)
    message(STATUS "Found CUDAToolkit v${CUDA_VERSION_STRING}")
    set(HAVE_CUDA true)
    set(CMAKE_CUDA_ARCHITECTURES "75;80;86")
    set(CMAKE_CUDA_COMPILER_LIBRARY_ROOT /usr/local/cuda)
else()
    message(STATUS "CUDA was not found.")
endif()
